name: 'Tauri Build'
description: 'Build a Tauri App and upload the bundled binaries and artifacts to a GitHub release.'
author: 'okcodes'

branding:
  icon: 'package'
  color: 'yellow'

inputs:
  tauriContext:
    description: 'Folder to the source code of the app. A file "src-tauri/Cargo.toml" must exist inside that folder.'
    required: true
  buildOptions:
    description:
      (required if "skipBuild" is "false") Options sent to the tauri build command. You must specify the "--target" flag. E.g., "--target aarch64-apple-darwin --bundles 'app,dmg,updater'". Run "pnpm run build --help" for more info.
    required: false
  expectedArtifacts:
    description: (required if "skipBuild" is "false") The expected number of app files to find after the build. The action fails if this number is not met.
    required: false
  tagTemplate:
    description:
      '(optional and mutually exclusive with "releaseId", action will fail if both are set) Template to generate the tag name of the release. It will interpolate "{NAME}" and "{VERSION}" with the app name and version defined in
      "src-tauri/Cargo.toml".'
    required: false
  releaseId:
    description:
      '(optional and mutually exclusive with "tagTemplate", action will fail if both are set) If you know in advance the ID of the release where to upload the app. It is highly recommendable that if "skipBuild" is false, you use this field,
      see why: https://github.com/okcodes/tauri-build/issues/9'
    required: false
  prerelease:
    description: 'If the GitHub release to create should be marked as prerelease.'
    required: true
  draft:
    description: 'If the GitHub release to create should be marked as draft.'
    required: true
  skipBuild:
    description: 'If set to "true", the app will not be built, and only the GitHub release will be created. It is highly advisable that if this is false, you use a "releaseId", see why: https://github.com/okcodes/tauri-build/issues/9'
    required: true
    default: 'false'

outputs:
  appName:
    description: 'Name of the app as defined in the "src-tauri/Cargo.toml" file.'
  appVersion:
    description: 'Version of the app as defined in the "src-tauri/Cargo.toml" file.'
  tag:
    description: 'Tag used in the GitHub release.'
  releaseId:
    description: 'ID of the release obtained or created where the app assets were uploaded after building the app.'

runs:
  using: node20
  main: dist/index.js
