name: 'Tauri Build'
description: 'Build a Tauri App and upload the bundled binaries and artifacts to a GitHub release.'
author: 'okcodes'

branding:
  icon: 'package'
  color: 'yellow'

inputs:
  tauriContext:
    description: 'Folder to the source code of the app. A file "src-tauri/Cargo.toml" must exist inside that folder.'
    required: true
  buildOptions:
    description: Options sent to the tauri build command. You must specify the "--target" flag. E.g., "--target aarch64-apple-darwin --bundles 'app,dmg,updater'". Run "pnpm run build --help" for more info.
    required: true
  expectedArtifacts:
    description: The expected number of app files to find after the build. The action fails if this number is not met.
    required: true
  tagTemplate:
    description: 'Template to generate the tag name of the release. It will interpolate "{NAME}" and "{VERSION}" with the app name and version defined in "src-tauri/Cargo.toml".'
    required: true
  prerelease:
    description: 'If the GitHub release to create should be marked as prerelease.'
    required: true
  draft:
    description: 'If the GitHub release to create should be marked as draft.'
    required: true

outputs:
  appName:
    description: 'Name of the app as defined in the "src-tauri/Cargo.toml" file.'
  appVersion:
    description: 'Version of the app as defined in the "src-tauri/Cargo.toml" file.'
  tag:
    description: 'Tag used in the GitHub release.'
  releaseId:
    description: 'ID of the release obtained or created where the app assets were uploaded after building the app.'

runs:
  using: node20
  main: dist/index.js
